<a href="https://colab.research.google.com/github/2303A51171/2303A51171-2025BT17-18/blob/main/2303A51171_Lab3_PDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
B=np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])
print("Matrix A:\n",A)
print("Matrix b:\n",B)
print("A+B:\n",np.add(A,B))
print("A-B:\n",np.subtract(A,B))

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix b:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A+B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A-B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [3]:
import numpy as np
A=np.array([[1,2],
            [3,4],
            [5,6]])
B=np.array([[7,8,9],
            [10,11,12]])
print("Matrix A (3x2):\n",A)
print("Matrix b (2x3):\n",B)
C=np.dot(A,B)
print("Result of AxB (3x3):\n",C)

Matrix A (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Matrix b (2x3):
 [[ 7  8  9]
 [10 11 12]]
Result of AxB (3x3):
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
